#ifndef __HT_PLATFORM_RESULTCODE_H__
#define __HT_PLATFORM_RESULTCODE_H__

#define HT_PLATFORM_RESULTCODE_SUCESS            0
#define HT_PLATFORM_RESULTCODE_NOUSER           -1
#define HT_PLATFORM_RESULTCODE_ERRORPSWD        -2
#define HT_PLATFORM_RESULTCODE_NOPOWER_ADDUSER     -3
#define HT_PLATFORM_RESULTCODE_MODIFY_PASSWD_ERROR      -4
#define HT_PLATFORM_RESULTCODE_ERROR    -5
#endif // __HT_PLATFORM_RESULTCODE_H__
